// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/13/2025, 1:32:16 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/plugins/**/*.{js,ts,mjs}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/composables/**/*.{js,ts,mjs}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/utils/**/*.{js,ts,mjs}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ecloudvalley/Documents/ecv-projects/gsis/llmchats/gsis-poc-web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;